default:
  http_metas:
    content-type: text/html

  metas:
    title:        HindiWorth.COM &raquo; Development By DabangWap.IN
    robots:       index, follow
    language:     en

  stylesheets:    []

  javascripts:    []

  has_layout:     on
  layout:         layout
